proxy:
  microleaves:
    api:
      membership: kQe7
      token: PVjOL9fLwLmszLvIMshXhS8mb6U5DeeANmgPEfF9q8Of5ZTnNvIxdQjNqG5xOR82
    host: 51.15.13.145
    ports:
      br:
      - 3051
      - 3052
      ru:
      - 3053
      - 3054
      de:
      - 3055
      - 3056
      in:
      - 3057
      - 3058
      nz:
      - 3059
      - 3060
      gb:
      - 3061
      - 3062
      es:
      - 3063
      - 3064
      fr:
      - 3065
      - 3066
      it:
      - 3067
      - 3068
      ca:
      - 3069
      - 3070
      tw:
      - 3071
      - 3072
      us:
      - 3073
      - 3074
      - 3075
      #
      ae:
      - 3051
      - 3052
      au:
      - 3053
      - 3054
      id:
      - 3055
      - 3056
      jp:
      - 3057
      - 3058
      kr:
      - 3059
      - 3060
      mx:
      - 3061
      - 3062
      nl:
      - 3063
      - 3064
      za:
      - 3065
      - 3066
      my:
      - 3067
      - 3068
      cn:
      - 3069
      - 3070
      th:
      - 3071
      - 3072
      hk:
      - 3073
      - 3074
      - 3075
      #
      sg:
      - 3051
      - 3052
      - 3053
      vn:
      - 3054
      - 3055
      - 3056
      pt:
      - 3057
      - 3058
      - 3059
      tr:
      - 3060
      - 3061
      - 3062
      ar:
      - 3063
      - 3064
      - 3065
      sa:
      - 3066
      - 3067
      qa:
      - 3068
      - 3069
      kw:
      - 3070
      - 3071
      eg:
      - 3072
      - 3073
      ir:
      - 3074
      - 3075
